# 3

In [32]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from lightgbm import LGBMClassifier as lgb

In [33]:
train = pd.read_csv("archive/mnist_train.csv")

In [34]:
x=train.iloc[:,1:]
y=train.iloc[:,0]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [36]:
rf=RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
pred = rf.predict(X_test)

In [37]:
from sklearn.metrics import classification_report, confusion_matrix


print(classification_report(y_test, pred))
confusion_matrix(y_test, pred)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1510
           1       0.99      0.99      0.99      1728
           2       0.96      0.97      0.96      1458
           3       0.97      0.95      0.96      1548
           4       0.97      0.97      0.97      1434
           5       0.97      0.96      0.96      1342
           6       0.98      0.98      0.98      1468
           7       0.97      0.97      0.97      1535
           8       0.96      0.96      0.96      1484
           9       0.95      0.96      0.95      1493

    accuracy                           0.97     15000
   macro avg       0.97      0.97      0.97     15000
weighted avg       0.97      0.97      0.97     15000



array([[1494,    0,    1,    0,    3,    1,    3,    1,    7,    0],
       [   0, 1707,    8,    5,    2,    1,    1,    2,    1,    1],
       [   3,    1, 1408,    8,    8,    2,    4,   14,    8,    2],
       [   2,    1,   17, 1474,    0,   16,    1,   14,   15,    8],
       [   2,    2,    2,    0, 1389,    0,    7,    6,    3,   23],
       [  10,    1,    4,   13,    4, 1286,   10,    1,    7,    6],
       [   4,    4,    1,    0,    3,   13, 1440,    0,    3,    0],
       [   1,    4,   17,    0,    6,    0,    0, 1487,    3,   17],
       [   1,    7,    9,    7,    5,    9,    8,    0, 1426,   12],
       [   2,    4,    0,   18,   17,    4,    1,   10,   10, 1427]])

In [38]:
cv_score = cross_val_score(rf, x, y)
print (np.mean(cv_score))

0.9662666666666666


In [39]:
gb = lgb(n_estimators=100)

gb.fit(X_train, y_train)

pred = gb.predict(X_test)

print(classification_report(y_test, pred))
confusion_matrix(y_test, pred)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1510
           1       0.99      0.99      0.99      1728
           2       0.96      0.97      0.97      1458
           3       0.97      0.97      0.97      1548
           4       0.97      0.98      0.97      1434
           5       0.97      0.96      0.97      1342
           6       0.98      0.98      0.98      1468
           7       0.98      0.98      0.98      1535
           8       0.96      0.98      0.97      1484
           9       0.97      0.97      0.97      1493

    accuracy                           0.98     15000
   macro avg       0.98      0.98      0.98     15000
weighted avg       0.98      0.98      0.98     15000



array([[1491,    0,    2,    0,    2,    3,    4,    0,    8,    0],
       [   0, 1709,    8,    4,    2,    0,    0,    1,    3,    1],
       [   2,    2, 1418,   11,    5,    0,    2,   11,    6,    1],
       [   2,    0,   10, 1502,    0,   11,    0,    7,    9,    7],
       [   2,    0,    3,    0, 1402,    0,    2,    3,    3,   19],
       [   6,    2,    4,   17,    4, 1292,    7,    0,    7,    3],
       [   4,    3,    4,    0,    6,   13, 1434,    1,    3,    0],
       [   1,    3,   14,    1,    6,    0,    0, 1497,    3,   10],
       [   2,    4,    8,    0,    1,    3,    9,    0, 1450,    7],
       [   1,    2,    1,    8,   14,    7,    1,    6,   11, 1442]])

In [40]:
cv_score = cross_val_score(gb, x, y)
print (np.mean(cv_score))

0.9750666666666665


# 4

In [41]:
train = pd.read_csv("cifar10/train.csv")
x=train.iloc[:,1:]
y=train.iloc[:,0]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [48]:
rf=RandomForestClassifier(n_estimators=100, n_jobs=5)

rf.fit(X_train, y_train)
pred = rf.predict(X_test)

print(classification_report(y_test, pred))
confusion_matrix(y_test, pred)

              precision    recall  f1-score   support

           0       0.59      0.77      0.67        66
           1       0.38      0.73      0.50        77
           2       0.20      0.19      0.19        48
           3       0.18      0.24      0.21        34
           4       0.16      0.09      0.12        43
           5       0.09      0.06      0.07        31
           6       0.14      0.16      0.15        31
           7       0.06      0.04      0.04        28
           8       0.15      0.14      0.14        37
           9       0.06      0.06      0.06        33
          10       0.04      0.04      0.04        27
          11       0.03      0.04      0.03        26
          12       0.04      0.03      0.03        32
          13       0.05      0.05      0.05        40
          14       0.09      0.11      0.10        38
          15       0.00      0.00      0.00        43
          16       0.00      0.00      0.00        36
          17       0.10    

array([[ 51,  13,   1, ...,   0,   0,   0],
       [ 10,  56,   4, ...,   0,   0,   0],
       [  6,  17,   9, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   3,   6,  53],
       [  0,   0,   0, ...,   2,  10,  69],
       [  0,   0,   0, ...,   0,   1, 595]])

In [49]:
gb = lgb(boosting_type='gbdt', 
                 objective='multiclass', num_class=10,
                 num_iteration=100, max_depth=4, learning_rate=0.01, 
                 n_estimators=100, nthread=4, silent=False)

gb.fit(X_train, y_train)

pred = gb.predict(X_test)

print(classification_report(y_test, pred))
confusion_matrix(y_test, pred)

/Users/saiansh/opt/anaconda3/lib/python3.9/site-packages/lightgbm/engine.py:148: UserWarning: Found `num_iteration` in params. Will use it instead of argument
  _log_warning("Found `{}` in params. Will use it instead of argument".format(alias))


[LightGBM] [Warning] num_threads is set with nthread=4, will be overridden by n_jobs=-1. Current value: num_threads=-1
[LightGBM] [Warning] num_iterations is set=100, num_iteration=100 will be ignored. Current value: num_iterations=100
[LightGBM] [Warning] num_threads is set with nthread=4, will be overridden by n_jobs=-1. Current value: num_threads=-1
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.744753 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 750110
[LightGBM] [Info] Number of data points in the train set: 37500, number of used features: 3072
[LightGBM] [Info] Start training from score -5.143024
[LightGBM] [Info] Start training from score -5.098374
[LightGBM] [Info] Start training from score -5.649294
[LightGBM] [Info] Start training from score -5.744604
[LightGBM] [Info] Start training from score -5.907123
[LightGBM] [Info] Start training from score -6.043460
[LightGBM] [Info] Start t

array([[ 58,   5,   1, ...,   0,   0,   0],
       [  7,  59,   7, ...,   0,   0,   0],
       [  3,  11,  15, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,  36,   5,  18],
       [  0,   0,   0, ...,   4,  55,  20],
       [  0,   0,   0, ...,   2,   7, 585]])